### ISSUE TITLE
DTR 0.4.3 (R24.08) Helm Deployment Fails for `enablePostgres: false`

### ISSUE THREAD

**Issue by jerzy-wachowiak** [eclipse-tractusx/sldt-digital-twin-registry#452]
# Setup
dtr 0.4.3 is mandatory for R24.08 "Jupiter" → we use external DB activated with the configuration
`enablePostgres: false`  and
```
  dataSource:
    driverClassName: org.postgresql.Driver
    sqlInitPlatform: pg
    ## The url, user, and password parameter will be ignored if 'enablePostgres' is set to true.
    ## In that case the postgresql auth parameters are used.
    url: "XXX"
    user: "XXX"
    password: "XXX"
```
This configuration worked in the past.

# Problem
Helm deployment fails with:
`Error: INSTALLATION FAILED: context deadline exceeded`

Pod description expert:
```
Events:
  Type     Reason     Age                 From               Message
  ----     ------     ----                ----               -------
  Normal   Scheduled  108s                default-scheduler  Successfully assigned bpnl000000000nph-stg44/dtr043-digital-twin-registry-5c987bdb85-rcgjf to aks-agentpool-31089915-vmss00000g
  Normal   Pulled     6s (x10 over 108s)  kubelet            Container image "docker.io/tractusx/sldt-digital-twin-registry:0.3.23" already present on machine
  Warning  Failed     6s (x10 over 108s)  kubelet            Error: secret "secret-dtr-postgres-init" not found
```
[postgres-init.yaml](charts/registry/templates/registry/postgres-init.yaml) doesn't seem to support the setup with `enablePostgres: false` ❓
