### ISSUE TITLE
Enable OAuth2 Security for Digital Twin Registry / AAS Rest-API

### ISSUE THREAD

**Issue by factoryX-ML** [eclipse-tractusx/sldt-digital-twin-registry#503]
Description

We have configured a keycloak for the digital twin registry (DTR) and DTR application failed to start [1].
OAuth2 security is not working for DTR: without a valid token from the authorization server you can access the aas rest api.

Steps to Reproduce
    1) Configure a authorization server like keycloak for DTR [2].
    2) Start DTR with issuer-uri.

Expected Behavior

- The DTR start up successfully and is secured as expected. Without having a valid bearer token from the configured authorization server with the client roles needed, the aas api is not usable.

- So the aas api is only accessible with a valid bearer token in the request header.

Possible Solution
 
- Possible successful testet solution [3] could be to define a JwtDecoder Bean for the issuer configuration and enable Spring Boot security by using @EnableWebSecurity annotation as recommended in the spring documentation, also see https://docs.spring.io/spring-security/reference/servlet/oauth2/index.html.

[1] Cutted DTR application log for DTR with configured issuer-uri:
```
***************************
APPLICATION FAILED TO START
***************************

Description:

Method configure in org.eclipse.tractusx.semantics.registry.security.OAuthSecurityConfig required a bean of type 'org.springframework.security.oauth2.jwt.JwtDecoder' that could not be found.


Action:

Consider defining a bean of type 'org.springframework.security.oauth2.jwt.JwtDecoder' in your configuration.


Process finished with exit code 1
```

[2] DTR example configuration (using properties) with local keycloak as issuer:
```
security:
  oauth2:
    resourceserver:
      jwt:
        issuer-uri: "http://localhost:8081/realms/default-realm"

registry:
  external-subject-id-wildcard-prefix: PUBLIC_READABLE
  external-subject-id-wildcard-allowed-types: manufacturerPartId,assetLifecyclePhase
  idm:
    public-client-id: default-client
    owningTenantId: TENANT_ONE
    identity-provider: keycloak
```

[3] Possible solution as code snippet defining conditional jwt decode bean & add @EnableWebSecurity annotation in existing OAuthSecurityConfig.class
```
@Profile("!local")
@Configuration
@EnableWebSecurity
public class OAuthSecurityConfig {


	@Bean(name = "jwtDecoderWithIssuerLocation")
	@ConditionalOnProperty(prefix="security.oauth2.resourceserver.jwt", name="issuer-uri")
	public JwtDecoder jwtDecoderWithIssuerLocation(@Value( "${security.oauth2.resourceserver.jwt.issuer-uri}") String issuerUri) {
		return JwtDecoders.fromIssuerLocation(issuerUri);
	}
	...
}

```
